spring:
  application:
    name: Registration

  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #NOT working these properties
    dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9090
